### ISSUE TITLE
progress bar for deploy (publish)  process

### ISSUE THREAD

**Issue by RezaHaidari** [fandoghpaas/fandogh-cli#1]
thanks for such awesome product, it would be nice if service display a progress bar during deploy process.

**Comment by s-soroosh** [comment]
Hi @RezaHaidari, 
Thanks for mentioning this indeed useful feature.
For now I have added a new command that you can use to see the log result of your docker build:
`fandogh app  inspect --app=$YOUR_APP_NAME --version=$YOUR_VERSION`

however it cannot show the progress so far as it will be accessible once image building is done, either successfully or by error. 

Will implement the progress as part of the fandogh version 0.2.

**Comment by s-soroosh** [comment]
@RezaHaidari 

now build progress will be show on publish command by default. 
you can disable it by passing `-d` command that detaches the terminal.

Thanks for sharing you opinion.
