### ISSUE TITLE
workspace limitation

### ISSUE THREAD

**Issue by blackavec** [fandoghpaas/fandogh-cli#104]
hey guys, 
i just started testing fandogh and the idea is awesome.
although in my second attempt to test the reliability of the service, i failed to deploy due to size of my workspace.
apparently limitation has set to be less than 20MB.
i understand that a normal apps like MVPs are usually small but i attempted to lunch a simple GraphQL app on top of typescript, and it's 26MB so far.
i'm not sure what is this limitation based on but i believe it's little too less.
would it be possible to increase at least to 50MB or even 100MB???

also is there any plan to extend the terraform to support fandogh as well?
if not, i might be able to spare some times and contribute 🔨

**Comment by s-soroosh** [comment]
Hi @blackavec, 

Thanks for your feedback.

Actually it was supposed to be just a warning. 
However our ingress rule had also hard limit on the body size that I just increased.  
As the result now you should be able to publish bigger workspaces.

The main idea behind this limitation is to have self contained build Dockerfiles. So fandogh image builder will fetch all the dependencies your image need to have regarding your dockerfile. I guess you have some files in your workspace that can be fetched from artefact servers like npm.

Regarding the terraform for the time being we don't have any plan yet. we are working on fandogh manifests to simplify the deployments and managements. 
But of course we appreciate if you could contribute on this topic. LMK if you are willing to discuss more about it :)

**Comment by blackavec** [comment]
hey @psycho-ir 
thanks for reply,

i understand the approach and it's very intelligent idea, how ever, i guess it needs some additional parts.
like ignore the files in `.dockerignore` when the size of workspace is being calculated.
i already forked the cli and tested that limitation on my own machine and even after raising the limitation manually, the api.fandogh.cloud doesn't accept it. so maybe you can check that out as well. (although i guess by updating the ingress config, it already being fixed 👍)

regarding the terraform, i'd be more than happy to contribute. although i have one concern.
since the basic free plan only allows users to have 2 running services at the same time, i guess therefrom would be just a luxury at this time but defiantly in the future will be a game changer.

i'm also curious to know what is the strategy for autoscaling for pods. do you guys wanna implement it any time soon(i understand that the demand rate is not high at the moment).

regarding contribution, i'd be more than happy to have a hand in this cool idea.
i'm very busy at this point during my office hours but after that i can squeeze fandogh into my personal activities. 
do you guys have any public Slack?

**Comment by s-soroosh** [comment]
@blackavec Regarding the size calculation it must be done on zipped workspace that does not include the ignored files via `.dockerignore`. do you see different behaviour? 

Yes the problem should be fixed now. plz kindly try again and cofirm it.

We will tackle the autoscaling in our milestone 0.7. that shouldn't be very far (probably by 4 weeks)
I guess we now need to setup our public slack channel as well  👍  will set it up and announce it here and in the twitter.

**Comment by blackavec** [comment]
@psycho-ir awesome bro.
i'll test it soon, i'm busy ATM.
cannot wait to see that scaling feature.
also just a question. do you guys have any plan to have something like AWS EMR or AWS GLUE in your managed services??? 
[question] i know it's not a demanding service but we are managing stuff on amazon which for a big/well funded Corp is not a big deal in terms of costs but for small startups is a bit pricy so maybe you guys can provide users with these kind of features as well

**Comment by s-soroosh** [comment]
As you also mentioned it definitely depends on the demands. 
We have this possibility to provide such services as `managed service`. So once we had reasonable amount of requests for them we of course consider to provide them as well.

**Comment by blackavec** [comment]
awesome cannot wait to see more features. 👍
