### ISSUE TITLE
500 Server Error: Internal Server Error ("Cannot locate specified Dockerfile: Dockerfile")

### ISSUE THREAD

**Issue by blackavec** [fandoghpaas/fandogh-cli#111]
this happened on `fandogh image publish`
this link might help: https://stackoverflow.com/questions/36236491/docker-compose-gives-error-cannot-locate-specified-dockerfile-dockerfile

**Comment by s-soroosh** [comment]
Hi @blackavec,
Are you sure you have Dockerfile in your workspace root directory?

**Comment by blackavec** [comment]
@psycho-ir  yes, i do have Dockerfile in my workspace
<img width="133" alt="image" src="https://user-images.githubusercontent.com/3764096/43735263-c9e68f2c-99ec-11e8-852c-1752b085dd75.png">

**Comment by s-soroosh** [comment]
@blackavec could you please share the content of .dockerignore  here

**Comment by blackavec** [comment]
sure
```
.git
*Dockerfile*
*docker-compose*
node_modules
dist
```

**Comment by s-soroosh** [comment]
@blackavec you ignored it :D
*Dockerfile*
fandogh doesn't include the excluded files inside the workspace zip file.

**Comment by blackavec** [comment]
cool works now, thanks bro

**Comment by s-soroosh** [comment]
Great, have fun with fandogh :)
