### ISSUE TITLE
DeprecationWarning in `fandogh image list` command

### ISSUE THREAD

**Issue by ecdesa** [fandoghpaas/fandogh-cli#125]
fandogh-cli version: 0.5.9
python version: 3.7.0

I'm receiving this warning after running the command `fandogh image list`:

> python37/lib/site-packages/beautifultable/beautifultable.py:433: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
>   if not isinstance(value, collections.Iterable) or isinstance(value, str):

**Comment by s-soroosh** [comment]
Thanks for reporting. 
We'll check it ASAP.
