### ISSUE TITLE
`fandogh image delete` cant accept image name argument

### ISSUE THREAD

**Issue by ecdesa** [fandoghpaas/fandogh-cli#126]
fandogh-cli version: 0.5.9

Right now in order to delete an image you have to run `fandogh image delete` and then enter the image name in the interactive shell.
Not only this adds an unnecessary step to removing images it also makes it impossible to use this command in shell scripts.
You can solve this issue by accepting one or more image name arguments in the command.

**Comment by s-soroosh** [comment]
Hi @mohamadnorouzi20 

You can pass it in first place via `--image` or `-i` option.
e.g. ` fandogh image delete --image YOUR_IMAGE_NAM`

By passing `--help` option to each command you can see the possible options.
e.g. `fandogh image delete --help`

**Comment by ecdesa** [comment]
oh ok, my fault.
