### ISSUE TITLE
image init error command returns: "internal error"

### ISSUE THREAD

**Issue by farbodrashidi** [fandoghpaas/fandogh-cli#131]
hey there,

after running image init command i get the following error:

```
farbod@universe ~/fandogh> fandogh image init
image name: gitlab
Sorry, there is an internal error, the incident has been logged and we will fix it ASAP
```

p.s.: where are the logs anyways?

**Comment by MahdiZareie** [comment]
Thank you for your report
This is an internal error and we're investigating it right now.
by log, we mean our log files in fandogh server.
