### ISSUE TITLE
fandogh service list command returns error

### ISSUE THREAD

**Issue by farbodrashidi** [fandoghpaas/fandogh-cli#132]
hi,

after a week or so I was to experiment with fandogh again, so I wanted to see what service i am currently running, but it shows me this error which obviously is about beautifultable package:

```
farbod@universe ~/fandogh> fandogh service list
/usr/lib/python3.7/site-packages/beautifultable/beautifultable.py:433: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  if not isinstance(value, collections.Iterable) or isinstance(value, str):
```
if you need any further info, just let me know.

**Comment by MahdiZareie** [comment]
Thank you for your report.
It's not an error, this is just a DeprecationWarning,
you shouldn't have any problem listing services, is there any other output?

**Comment by MahdiZareie** [comment]
Duplicate issue #125
