### ISSUE TITLE
Installing fandogh-cli Failed!

### ISSUE THREAD

**Issue by nasrabadiAM** [fandoghpaas/fandogh-cli#141]
When I try to install fandogh-cli on ubuntu 18.04, intallation ends with this:

> Installing collected packages: six, enum34, idna, asn1crypto, pycparser, cffi, ipaddress, cryptography, pyOpenSSL, pytz, tzlocal, certifi, chardet, urllib3, requests, requests-toolbelt, click, beautifultable, pyyaml, fandogh-cli
> Successfully installed asn1crypto-0.24.0 beautifultable-0.5.2 certifi-2018.8.24 cffi-1.11.5 chardet-3.0.4 click-6.7 cryptography-2.3.1 enum34-1.1.6 fandogh-cli-0.7.0 idna-2.7 ipaddress-1.0.22 pyOpenSSL-18.0.0 pycparser-2.18 pytz-2018.5 pyyaml-3.13 requests-2.19.1 requests-toolbelt-0.8.0 six-1.11.0 tzlocal-1.5.1 urllib3-1.23
> Segmentation fault (core dumped)
> 

And fandogh-cli doesn't installed.

**Comment by s-soroosh** [comment]
Hi @nasrabadiAM ,

could you please share the output of these 3 commands with us?
`python --version`
`pip --version`
`pip install fandogh_cli --upgrade -vvv`

**Comment by nasrabadiAM** [comment]
Hi @psycho-ir  And Thanks for your quick response, 

these are the result of each commands:

> python --version = **Python 2.7.15rc1**

> pip --version = **pip 9.0.1 from /usr/lib/python2.7/dist-packages (python 2.7)**

> pip install fandogh_cli --upgrade -vvv 

This command ends with this:
```
Installing collected packages: six, enum34, idna, asn1crypto, pycparser, cffi, ipaddress, cryptography, pyOpenSSL, pytz, tzlocal, certifi, chardet, urllib3, requests, requests-toolbelt, click, beautifultable, pyyaml, fandogh-cli













  changing mode of /home/alinasrabadi/.local/bin/chardetect to 755







  changing mode of /home/alinasrabadi/.local/bin/fandogh to 755
Successfully installed asn1crypto-0.24.0 beautifultable-0.5.2 certifi-2018.8.24 cffi-1.11.5 chardet-3.0.4 click-6.7 cryptography-2.3.1 enum34-1.1.6 fandogh-cli-0.7.0 idna-2.7 ipaddress-1.0.22 pyOpenSSL-18.0.0 pycparser-2.18 pytz-2018.5 pyyaml-3.13 requests-2.19.1 requests-toolbelt-0.8.0 six-1.11.0 tzlocal-1.5.1 urllib3-1.23
Cleaning up...
Segmentation fault (core dumped)
```
And its full output is in **[result.txt](https://github.com/fandoghpaas/fandogh-cli/files/2322623/result.txt)** file.

**Comment by s-soroosh** [comment]
@nasrabadiAM It's more look like an issue with the environment. 
as error is happening in cleaning up of the pip.

could you please update you pip? the latest version should be 18. 

and the python you are using is rc (release candidate) would be better to upgrade it to the stable version. 
https://www.python.org/downloads/release/python-2715/

Feel free to contact us if these upgrades didn't fix your issue.

**Comment by nasrabadiAM** [comment]
Upgrading pip version doesn't work properly, and finally i installed fandogh-cli manually from its source with:

> python setup.py install

Thank you for your help. 
Good luck.

**Comment by s-soroosh** [comment]
@nasrabadiAM Good to hear that.
However I highly recommend you install the fandogh-cli via `pip` as we release new version in daily basis and you need to put more effort to update the `cli`. 
This script might help:
```
curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
python get-pip.py
```

**Comment by nasrabadiAM** [comment]
Thanks @psycho-ir for that script, it works fine and finally I installed `fandogh-cli` with `pip`.
I will follow your recommandation to be update.

Thanks a lot,
Good luck.
