### ISSUE TITLE
fandogh service list Failed

### ISSUE THREAD

**Issue by savyjs** [fandoghpaas/fandogh-cli#144]
hi ,
what it means?
```
Sorry, there is an internal error, the incident has been logged and we will fix it ASAP
```

1- I got this after service list
```
 fandogh service list
Sorry, there is an internal error, the incident has been logged and we will fix it ASAP
```
and
2- after deploying a service .

**Comment by s-soroosh** [comment]
Hi @savyir,
Thanks for reaching us out.

Do you still have this issue?

could you try again?

**Comment by savyjs** [comment]
@psycho-ir yes, still the same. 

```
 fandogh service list
Sorry, there is an internal error, the incident has been logged and we will fix it ASAP
```

``` 
 fandogh service deploy -p 8080
The image version: 1.0.2
Your service name: savvyversa
Sorry, there is an internal error, the incident has been logged and we will fix it ASAP
```

what is this error ?

**Comment by s-soroosh** [comment]
@savyir Thank you for reporting the issue.
Yes indeed there was as issue that caused for a few namespaces service commands not working.

This issue should already be fixed.
May I kindly ask you to confirm?

**Comment by savyjs** [comment]
Yes , it's ok now. 
Thank you @psycho-ir
