### ISSUE TITLE
shared-storage 

### ISSUE THREAD

**Issue by mansourmahboubi** [fandoghpaas/fandogh-cli#145]
Hi, 
is there a way to access shared-storage remotely for backup?

**Comment by s-soroosh** [comment]
Hi @mmans0ur, 

Thanks for reaching us out. 
No unfortunately it's not possible at the moment. 
But we are working on a solution for non free users to get back from their volumes and get access to the backups through our object storage.

**Comment by mansourmahboubi** [comment]
Thanks @psycho-ir ,
I'll be glad to be informed about improvements

**Comment by s-soroosh** [comment]
@mmans0ur sure thing. will notify you on our progress regarding backup.

**Comment by s-soroosh** [comment]
@mmans0ur , 

I opened issue #151  that address your requirement.

**Comment by mansourmahboubi** [comment]
@psycho-ir , thx for the great support
