### ISSUE TITLE
show progress bar for workspace upload job

### ISSUE THREAD

**Issue by s-soroosh** [fandoghpaas/fandogh-cli#15]
It's helpful to show the user how long it takes to publish the workspace.
Ideally we should give some warning to the user if the workspace size is more than usual. e.g. > 20MB
and give him some hint how to use .dockerignore feature.

**Comment by MahdiZareie** [comment]
Shouldn't we have an API for these limitations?

**Comment by s-soroosh** [comment]
No not yet. A fixed size is good enough for now

**Comment by MahdiZareie** [comment]
the warning regarding to workspace size has been done in #37
