### ISSUE TITLE
show logged in user and logging out command

### ISSUE THREAD

**Issue by ayooby** [fandoghpaas/fandogh-cli#159]
Fandogh-Cli does show login command when user is logged in which is not good IMO, it would be great if there was logout command instead.

As a user I need "who am I" command.

anyway thanks for your awesome project

**Comment by s-soroosh** [comment]
Hi @ayooby, 
Thank you so much for the feedbacks. 
Seems reasonable to have logout and whoami commands, we will add them in coming versions. 
But there are some use cases the logged in user wants to use `login` command again.
e.g. 
 - refresh token
 - change account in one shot

So we probably need to keep this command available even if the user is logged in, however we might find a better way to represent this to already logged in users.
