### ISSUE TITLE
SSL Certificate files

### ISSUE THREAD

**Issue by mehrancodes** [fandoghpaas/fandogh-cli#163]
Hello there!

Is there any option to get the ssl certificate files, since I think we don't have access to the `/etc/letsencrypt/live/....` after the certificate has been created.

**Comment by s-soroosh** [comment]
Hi @mehranrasulian,

You mean the default cert that fandogh creates for your subdomain?
The ssl connections in fandogh are terminated in load balancer level so from your service's perspective it's just a http request.
what is your use case?

**Comment by mehrancodes** [comment]
Yes, default cert.
But it's still fine!
So I'm gonna setup the Telegram webhook without cert files ;)

Thanks for quick response.
