### ISSUE TITLE
Unable to login when using CI tools

### ISSUE THREAD

**Issue by mehrancodes** [fandoghpaas/fandogh-cli#165]
Hello!

Seems it's easier to use a CI tool to publish and deploy the project after each commit.

I'm using GitLab CI and when it wants to login to Fandogh, a question msg will appear, so we can not answer it since the CI tools just show us a log page during the runtime.

```bash
$ pip install fandogh_cli
$ fandogh login --username my-username --password my-password
Would you like to let Fandogh CLI to send context information in case any unhandled error happens? [y/N]: Aborted!
ERROR: Job failed: exit code 1
```

Is it possible to add an option to the login command just to ignore or answer the question by -y or -n ?

Thanks!

**Comment by s-soroosh** [comment]
Hi @mehranrasulian 
You can set a env variable to ignore it. ‘COLLECT_ERROR’
See how it’s been used in this example:

https://github.com/fandoghpaas/fandogh-website/blob/master/.travis.yml

**Comment by mehrancodes** [comment]
Works like charm!
