### ISSUE TITLE
what is the cost of fandogh service?

### ISSUE THREAD

**Issue by MetaiR** [fandoghpaas/fandogh-cli#168]
Hi,
first of all, tnx for your great service. it is fun to work with it.
it is too good that this service is free and **I don't want to be rude** but I am just curious.

as u know we have a proverb in Iran for free services:

`هیچ ارزونی بی حکمت نیست`
which means: `nothing will be cheap without reason`

I am a developer too and aware that create and develop something like this service will not be cheap, so how is it free?

**Comment by s-soroosh** [comment]
Great to hear that you are enjoying our platform.

You are absolutely right, fandogh is not a free service. 
However we have free plan which consists of 2 running services (as long as we have enough extra resources to support them)

If you are interested to go further and run real products on fandogh, feel free to reach us out via support at fandogh dot cloud.

**Comment by MetaiR** [comment]
the free plan is very good for me and my projects actually.
I don't have enough money so unfortunately, I can't help u with the donation and other money related 
things but I love to help so is there any other way I can help u?

**Comment by s-soroosh** [comment]
That's really awesome for us to hear. 
Sure, reviewing the docs and working with project itself to give us feedback that how we can improve them is the biggest help. 

Would be great if you could help us in this regard.
