### ISSUE TITLE
CrashLoopBackOff

### ISSUE THREAD

**Issue by MetaiR** [fandoghpaas/fandogh-cli#170]
what does it mean, when does it happen and how to fix it?
![untitled](https://user-images.githubusercontent.com/7807264/46989814-77d39300-d10b-11e8-9141-59b98d8869b8.png)

(By the way, I used and followed the quick start steps and I faced to this problem on the last step (service deploy))

**Comment by s-soroosh** [comment]
Hi @MetaiR, 

CrashLoopBackoff error can have different root causes. But here it seems the reason relates to your code/container.

Try to build the docker image locally and run it to see if everything is working as expected.
