### ISSUE TITLE
Problem cli with Git Bash

### ISSUE THREAD

**Issue by Hesamp** [fandoghpaas/fandogh-cli#186]
When I use Windows **Git Bash**, it shows the **_password_** .
After entering the password, it will not login and crash
But **CMD** has no problem

**Comment by s-soroosh** [comment]
Hi @Hesamp, 
Thanks for reporting the issue. 

Could you plz share more info with us? like what error do you get in crash time if there is any?

**Comment by Hesamp** [comment]
There will be no error and the terminal order will not be canceled

`Hesam@DESKTOP-R19RBHJ MINGW64 ~
$ fandogh login
username: demo_test
password: demo_test`

**Comment by s-soroosh** [comment]
We will check it as soon as we find a windows machine around. 

Thanks again for reporting.
