### ISSUE TITLE
Case Sensitivity

### ISSUE THREAD

**Issue by 733amir** [fandoghpaas/fandogh-cli#192]
I am using `dockerfile` as the name of my dockerfiles but the tool doesn't seem to be able to find it.

**Comment by Anonycoders** [comment]
@733amir dear amir, thank you for the report.
actually we search for dockerfiles in CaseInSensetive mode, are you sure that your dockerfile is located in your root dir?

**Comment by 733amir** [comment]
Yes. When I renamed the file to `Dockerfile` everything worked correctly.

**Comment by Anonycoders** [comment]
@733amir we will check it ASAP.
thank's for the report

**Comment by 733amir** [comment]
I found the line that logs the error:
https://github.com/fandoghpaas/fandogh-cli/blob/ff7b72d3fc968800ef51748a612549dbaa68bd41/fandogh_cli/image_commands.py#L115

And I believe this is the line that check for the `dockerfile` and it seems case sensitive:
https://github.com/fandoghpaas/fandogh-cli/blob/4de598e8813b047eee236d3aa7650a78a1373325/fandogh_cli/workspace.py#L14

**Comment by 733amir** [comment]
I have created a pull request (#193) that solves the problem.
