### ISSUE TITLE
don't let user publish image with the existing version

### ISSUE THREAD

**Issue by s-soroosh** [fandoghpaas/fandogh-cli#20]

**Comment by MahdiZareie** [comment]
I believe this issue belong to API not the cli.

**Comment by s-soroosh** [comment]
@MahdiZareie I created all the issues here. as user won't see fandogh API issue board soon

**Comment by MahdiZareie** [comment]
I think we should use a label for these types of issues

**Comment by s-soroosh** [comment]
@MahdiZareie suggest something

**Comment by MahdiZareie** [comment]
what about `FandoghAPI` ?

**Comment by s-soroosh** [comment]
@MahdiZareie good
