### ISSUE TITLE
image publish workspace format can cause problem

### ISSUE THREAD

**Issue by EAliakbar** [fandoghpaas/fandogh-cli#200]
is there any specific reason for choosing zip format for workspace?
do to lack of storing Unix file attribute ability, zip format can cause different behaviors from building dockerfile locally

**Comment by s-soroosh** [comment]
Hi @EAliakbar,
We did it deliberately to reset the file attributes to avoid any security issue might happen on our build servers. 
I agree this can cause different behaviors though. 

Usually the only change that is needed is making the main file of the project executable.
