### ISSUE TITLE
Cannot uninstall 'PyYAML'. It is a distutils installed project

### ISSUE THREAD

**Issue by ftabashir** [fandoghpaas/fandogh-cli#207]
I tried to install fandogh cli using `pip install fandogh-cli` but I got this error: `Cannot uninstall 'PyYAML'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.`

Python 3.7.0
pip 19.0.3

**Comment by ftabashir** [comment]
You can find more info [here](https://github.com/pypa/pip/issues/5247)
I resolved my issue by downgrading pip using `pip install --upgrade --force-reinstall pip==9.0.3
` and then successfully installed fandogh-cli using `pip install fandogh-cli --disable-pip-version-check`

**Comment by rcrespo15** [comment]
worked for me while installing kedro
