### ISSUE TITLE
413 Request Entity Too Large

### ISSUE THREAD

**Issue by ftabashir** [fandoghpaas/fandogh-cli#208]
I installed wordpress and then tried to upload a theme which was 22 MB but I got this error:

> 413 Request Entity Too Large
> nginx/1.15.5

Why nginx returned such error?

**Comment by s-soroosh** [comment]
Hi @ftabashir, 
Thank you for reaching out. 
For security reasons we don't permit file uploads bigger than 20MB, unless users ask for. 
For the specific use case, I would highly recommend you build a docker image including the theme to have a immutable wordpress that you can redeploy wherever you want.
