### ISSUE TITLE
Removed free tire account without any alert

### ISSUE THREAD

**Issue by darius-khll** [fandoghpaas/fandogh-cli#217]
I had free account on fandogh and my services have been removed without any warning etc,
I want to know it was a bug or something you have known already which is going to happen or not?
my user on fandogh is "alikhll" though

**Comment by s-soroosh** [comment]
Hi Ali, 

Thanks for reaching us out. No this is not a bug in Fandogh. Free services are subject to be dropped if non free services need to more resources that already what already is available.

So this might happen from time to time.
