### ISSUE TITLE
Display appropriate message when there is no version available

### ISSUE THREAD

**Issue by MahdiZareie** [fandoghpaas/fandogh-cli#22]
it's nice to display a message, like `You didn't publish any version for this image` In `fandogh app versions` command when there isn't any version on the server

**Comment by MahdiZareie** [comment]
https://github.com/fandoghpaas/fandogh-cli/pull/24

**Comment by MahdiZareie** [comment]
Solved by #24

**Comment by s-soroosh** [comment]
at the moment cli is saying `Resource not found` for such cases. 
please return more friendly message.
