### ISSUE TITLE
HTTPSConnectionPool Error

### ISSUE THREAD

**Issue by MTaghaddomi** [fandoghpaas/fandogh-cli#243]
after attempting to login to cli this error occurred: 
Error in reporting problem. Please share this error with to help us to improve the service.
Caused by HTTPSConnectionPool(host='api.fandogh.cloud', port=443): Max retries exceeded with url: /api//api/latest-version (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available."))
Report error: 'dict' object has no attribute 'params'
Error in your network connection! trying again might help to fix this issue
if it is keep happening, please inform us!

**Comment by s-soroosh** [comment]
Hi @MortezaTaghaddomi99, 
As the error mentioned, the SSL module is not available in order to connect to https endpoints. 
Please ensure Openssl/Libressl is configured on your machine properly and then install fandogh cli. so it can install required packages.

**Comment by MTaghaddomi** [comment]
Thanks for your reply. I've been installed this package. The problem was my virtualenv configuration.
