### ISSUE TITLE
Image build problems

### ISSUE THREAD

**Issue by seantheyahn** [fandoghpaas/fandogh-cli#244]
In `fandogh, version 1.18.1`, when I try to build and push image I get this error (which looks like a connection timeout), however the image seems to be built and pushed successfully afterwards:

`Error in your network connection! trying again might help to fix this issue 
if it is keep happening, please inform us!
Error in reporting problem. Please share this error with to help us to improve the service.
Caused by ('Connection aborted.', BadStatusLine("''",))
Report error: Object of type ProtocolError is not JSON serializable`

Since I use a sequential script to change the version, build and tag a new image and deploy to the development server, this results in a failure of my script most of the times. 
It's worth noting that this wasn't a problem in previous cli versions.

**Comment by ahmdrz** [comment]
It's happened many times, even on Gitlab CI.

**Comment by s-soroosh** [comment]
Hi, Thanks for reporting this issue. 
A new change has been released 2 days ago, we believe that should fix the problem. 
Could you try again and let us know whether it's better or not?
