### ISSUE TITLE
fandogh cli issue

### ISSUE THREAD

**Issue by amireshoon** [fandoghpaas/fandogh-cli#245]
When I installed fandogh cli from `pip install fandogh-cli `command it successfully installed but `fandogh --version` or any other command with fandogh command not found in the system.
I tried in windows and ubuntu and get same issue.

**Comment by s-soroosh** [comment]
try to install with `pip3`

**Comment by amireshoon** [comment]
The package already installed but the environment didn't recognize.
However, I'll close the issue
