### ISSUE TITLE
Failed to run Fandogh CLI with "failed to create process" output

### ISSUE THREAD

**Issue by ShahryarSaljoughi** [fandoghpaas/fandogh-cli#248]
Though Installation of `fandogh-cli` completes successfully, running the `fandogh` commands results in the following message:  

> failed to create process.

OS: Windows 10
python version: 3.7.2
pip version: 20.1.1

I've tried to install it from the source, but it did not work either.

**Comment by s-soroosh** [comment]
The solutions mentioned here might help you to resolve this problem on your machine:
https://stackoverflow.com/questions/17373265/pip-easy-install-failure-failed-to-create-process

**Comment by ShahryarSaljoughi** [comment]
Thank you. I feel sorry to have you google it for me, though I had googled and found that solution myself.  
I had never renamed any part of python directory, so at the first glance [this solution](https://stackoverflow.com/questions/17373265/pip-easy-install-failure-failed-to-create-process) did not seem to help me. But still the problem was about the path to python.
path to python on my machine was something like this:  

    C:\Users\<FName>  <LName>\AppData\Local\Programs\Python\Python38-32\python

The problem was the `<Fname> <LName>`. The space in middle of the folder name was making trouble. I had it solved by renaming that folder and eliminating the space!
 
Hence, there is no problem with `fandogh-cli` itself. I hope, this would help others with the same problem.

**Comment by s-soroosh** [comment]
> Thank you. I feel sorry to have you google it for me, though I had googled and found that solution myself.
> I had never renamed any part of python directory, so at the first glance [this solution](https://stackoverflow.com/questions/17373265/pip-easy-install-failure-failed-to-create-process) did not seem to help me. But still the problem was about the path to python.
> path to python on my machine was something like this:
> 
> ```
> C:\Users\<FName>  <LName>\AppData\Local\Programs\Python\Python38-32\python
> ```
> 
> The problem was the `<Fname> <LName>`. The space in middle of the folder name was making trouble. I had it solved by renaming that folder and eliminating the space!
> 
> Hence, there is no problem with `fandogh-cli` itself. I hope, this would help others with the same problem.

Yes that was in the answers I sent you if you scrolled down enough ;). In such cases you can double quote the path.

**Comment by ShahryarSaljoughi** [comment]
Thanks a lot. wish you and your team the best.
I'll close this issue.
