### ISSUE TITLE
File permissions are lost in image publish

### ISSUE THREAD

**Issue by alisinabh** [fandoghpaas/fandogh-cli#249]
# Issue

File metadata such as attributes and permissions are not preserved when publishing an image with `fandogh image publish` command.

## Description

When publishing an image, The context data is uploaded into Fandogh servers for building an image.

These files and directories have attributes which will get **lost** in this procedure. For example an executable
`entrypoint.sh` file loses its executable flag and becomes unexecutable.

I believe this problem is caused because fandogh uses `zip` which won't take care of file permissions and attributes.
I suggest using tarball (`tar`) with gzip (`tar.gz`) extension to preserve file metadata.

## Version
```
# fandogh --version
fandogh, version 1.19.1
```

Thank you.

**Comment by ghost** [comment]
Hi @alisnabh

Thank you so much for raising this issue. We will address this problem soon. 
As a workaround you can set the necessary permissions inside the dockerfile via RUN chmod ... command. 
I know that it's not very convenient but should help you to proceed, in the meanwhile we will work on a fix for it.

**Comment by alisinabh** [comment]
Thank you @behroozmirzaie7 

I've fixed that but was really hard to debug indeed :)

**Comment by s-soroosh** [comment]
Thank you @alisinabh for the report. 
The bug is fixed in version `1.21.0`.
