### ISSUE TITLE
Let user specify the container port he wants to expose

### ISSUE THREAD

**Issue by s-soroosh** [fandoghpaas/fandogh-cli#26]
At the moment fandogh assumes the service is running on port 80.
would be nice to let the user to choose another port. 
suggestion:
add `-p` and `--port` options to service deploy.

**Comment by MahdiZareie** [comment]
I guess it's been implemented on the CLI and we can close this issue

**Comment by s-soroosh** [comment]
@MahdiZareie no not yet. the k8s branch on server side should finalise and merge first.
