### ISSUE TITLE
disk usage command error (du -h)

### ISSUE THREAD

**Issue by M-Amrollahi** [fandoghpaas/fandogh-cli#267]
I used the command [du -h] to see how much space have been used so far, but I got this error :
`Sorry, there is an internal error, the incident has been logged and we will fix it ASAP`

I used both [fandogh exec du -h] and [fandogh exec du]

Is there another way to have my disk usage?
Thanks,
Mahdi

**Comment by Anonycoders** [comment]
Dear @Mehdi-Amrollahi 
command that you are trying to use is not valid.
please consider reviewing related exec documents and step forward according to the samples provided there.
https://docs.fandogh.cloud/docs/exec.html
