### ISSUE TITLE
Got this problem when logging in

### ISSUE THREAD

**Issue by erfansaberi** [fandoghpaas/fandogh-cli#271]
Everything is working, just got this message when logging in.
```
Error in reporting problem. Please share this error with to help us to improve the service.
Caused by HTTPSConnectionPool(host='api.fandogh.cloud', port=443): Max retries exceeded with url: /api//api/latest-version (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x10D0B230>, 'Connection to api.fandogh.cloud timed out. (connect timeout=5)'))
Report error: 'dict' object has no attribute 'params'
```

**Comment by Anonycoders** [comment]
Dear @erfansaberi 
Thank you for reaching us out.
is the issue still there?
if so, please give us more informations like:
- what the OS is
- which approach did you use to install fandogh-cli
- how many times have you tried to log in fandogh account using fandogh-cli

**Comment by erfansaberi** [comment]
Hello @Anonycoders 
It just happened once, i never saw it again.
I'm using windows 10 and i used pip to install fandogh-cli. I don't remember how many times i tried to login, it should not have been more than two or three times.
