### ISSUE TITLE
PyYAML yaml.load Deprecation

### ISSUE THREAD

**Issue by Glyphack** [fandoghpaas/fandogh-cli#272]
the `yaml` method is deprecated and I get this warning when running `fandogh service apply -f`:

```fandogh_cli/service_commands.py:192: YAMLLoadWarning: calling yaml.load_all() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.```

**Comment by Anonycoders** [comment]
Dear @Glyphack 
Thank you for reaching us out.
We are aware of this warning and as the starting words of the line implies, it's just a warning.
So feel free to use fandogh-cli, we have your back ;)
