### ISSUE TITLE
Problem with .NET 5 docker images for deploy from source in ASP.NET Core projects

### ISSUE THREAD

**Issue by Hameds** [fandoghpaas/fandogh-cli#277]
There is a change in `.NET 5.0 SDK` url in docker hub. If we use deploy from source with `5.0` as .NET version CLI tries to find `mcr.microsoft.com/dotnet/core/sdk:5.0` which is wrong url. 

Here is the breaking change announcement: https://github.com/dotnet/dotnet-docker/issues/2375

Correct url is: `mcr.microsoft.com/dotnet/sdk:5.0`

**Comment by ghost** [comment]
Thank you so much for reaching out to us. 
ASP.net project has been added to the list of the supported projects.
Please initialize the project via fandogh source init and select ASP.net Project. 
Feel free top open a new issue in case you faced any issues. 

Regards,
