### ISSUE TITLE
login returns server error if username or pass is wrong

### ISSUE THREAD

**Issue by s-soroosh** [fandoghpaas/fandogh-cli#40]

**Comment by MahdiZareie** [comment]
I can't reproduce the issue, I tested with invalid username and invalid password both times I received `APIError. status code: 400, content: b'"Username or password is wrong"'`

**Comment by s-soroosh** [comment]
@MahdiZareie are you testing with the current version we have in pypi? `0.2.4`

**Comment by MahdiZareie** [comment]
Actually I wrote a test for API in the Fandogh codebase

**Comment by MahdiZareie** [comment]
Also tested with `master`, `0.2.4` and `0.2.3` ..still no luck in reproducing the issue
