### ISSUE TITLE
Document namespace and storage model

### ISSUE THREAD

**Issue by s-soroosh** [fandoghpaas/fandogh-cli#43]

**Comment by MahdiZareie** [comment]
@psycho-ir 
What do you think we should cover in this documentation?
I'm thinking about putting this image on top:
http://blog.fandogh.cloud/guide/fandogh-namespaces.png
and describe details regarding Namespace, private network, DNS server, shared storage and mount point after the image.
Is there anything else you think we should also cover?

**Comment by s-soroosh** [comment]
I gonna assign this issue to Sorena. 
Would be great to discuss with him at curate the reasonable materials for this section
