### ISSUE TITLE
Support internal services

### ISSUE THREAD

**Issue by s-soroosh** [fandoghpaas/fandogh-cli#44]
At the moment fandogh treats all the services as web. I.e exposes them on port 80.
However as we now support persistent there could be services like dbms that should only be accessible inside the namespace.

**Comment by s-soroosh** [comment]
Proposal:

for services that should not be exposed on http(s). e.g. DB
`
fandogh service deploy ... --type internal
`
for services that should be exposed on http(s). e.g. web services
`
fandogh service deploy ... --type external
`

@MahdiZareie @RezaHaidari  What do you think?

**Comment by MahdiZareie** [comment]
I suggest `--internal OR --external` instead of `--type SOME_STRING`, hmm? @psycho-ir

**Comment by s-soroosh** [comment]
@MahdiZareie  looks good to me

**Comment by MahdiZareie** [comment]
I implemented with just `--internal` switch, otherwise it's external
