### ISSUE TITLE
Deploy Superset on Fandogh

### ISSUE THREAD

**Issue by msadr-git** [fandoghpaas/fandogh-cli#80]
I want to ask how can I run this on fandogh?
https://github.com/Fokko/divolte-kafka-druid-superset

**Comment by s-soroosh** [comment]
Hi @tsadr,

Thanks for reaching us out about this interesting use case. 
Unfortunately at the time being each user can have 2 services running with 200MB memory for each.
And this stack needs several services:
 - zookeeper
 - kafka
 - divolte
 - druid console
 - druid indexing
 - superset

As the result it's not possible to run this stack with the free plan. 

However if you are interested to test our commercial plan, just do let me know. I will send you invitation to test it freely once we prepared it, might take ~2 months though.

Feel free to let us know more about your requirements and use cases you have.
