### ISSUE TITLE
Internal error happens with destroying a service

### ISSUE THREAD

**Issue by darius-khll** [fandoghpaas/fandogh-cli#81]
I created a service named "app-test" and after that creation succeed, I destroyed that and created with the same name service again
I do `fandogh service list` and then `fandogh service destroy` and I write the service name but it raises this error `Sorry, there is an internal error, the incident has been logged and we will fix it ASAP` consecutively!
Is there a way to force remove that specific service?

**Comment by MahdiZareie** [comment]
We're investigating the root cause of this error, Thank you for reporting the problem
Would you like me to delete your service manually? @Alikhll

**Comment by MahdiZareie** [comment]
The problem has been fixed and you shouldn't encounter the same problem while destroying services.
Please feel free to let us know if you encountered any problem again @Alikhll

**Comment by darius-khll** [comment]
Awesome, It has been fixed
