### ISSUE TITLE
problem with login and forgotten password

### ISSUE THREAD

**Issue by abbasnaqdi** [fandoghpaas/fandogh-cli#82]
I forgot my password and I can not login.
I also can not change my password!
How to reset my password?

**Comment by s-soroosh** [comment]
Hi,

Thanks for contacting us.
Did you try to recover your password and got error? 
You can recover you password by clicking on فراموشی رمز عبور in login modal.

**Comment by abbasnaqdi** [comment]
@psycho-ir I entered the website and used this option but ...
The operation is not done and there is no error.
this option does not work .

**Comment by s-soroosh** [comment]
Could you please send me your email address or username, operating system, borwser name and whether you are using http proxy or not?

Feel free to send your email address to soroosh.sarabadani@gmail.com if you are not willing to mention it here.

**Comment by abbasnaqdi** [comment]
I sent the email with the information you asked me.

**Comment by s-soroosh** [comment]
Thanks, I just registered your email address again.
Please let me know if the issue still exists
