### ISSUE TITLE
Support SSL on custom domain 

### ISSUE THREAD

**Issue by MahdiZareie** [fandoghpaas/fandogh-cli#99]

**Comment by MahdiZareie** [comment]
I added this issue in `0.4` milestone since having custom domain without SSL support is a bit useless

**Comment by MahdiZareie** [comment]
I believe this issue depends on #34

**Comment by s-soroosh** [comment]
Yes and that's why it shouldn't be part of mileston 0.4. 
Users can set ssl on thirdy CNDs like cloudflare.
